services:
    php:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
            args:
                CI_ENVIRONMENT: ${CI_ENVIRONMENT}
                DOCKER_PHP: ${DOCKER_PHP}
                DOCKER_PHP_PERSONAL: ${DOCKER_PHP_PERSONAL}
        restart: always
        environment:
            TZ: ${TZ}
        ports:
            - ${app_port}:${host_port}
        volumes:
            - ./app:/var/www/app
            - ./${DOCKER_COMPOSER}composer.json:/var/www/composer.json
            - ./${DOCKER_COMPOSER}composer.lock:/var/www/composer.lock
            - ./.env:/var/www/.env
            - ./html:/var/www/html
            - ${INPHP_E}:/inphp/e:ro
            - ${INPHP_G}:/inphp/g:ro
            - ${INPHP_L}:/inphp/l:ro
            - ${INPHP_M}:/inphp/m:ro
            - ${INPHP_P}:/inphp/p:ro
            - ${INPHP_PROJECT}:/inphp/project:ro
            - ${INPHP_S}:/inphp/s:ro
            - ./license:/var/www/license
            - ./module:/var/www/module
            - ./.php-cs-fixer.dist.php:/var/www/.php-cs-fixer.dist.php
            - ./phpstan.neon.dist:/var/www/phpstan.neon.dist
            - ./rector.php:/var/www/rector.php
        depends_on:
            - postgis
    postgis:
        build:
            context: ./
            dockerfile: ./docker/postgis/Dockerfile
            args:
                DOCKER_POSTGIS: ${DOCKER_POSTGIS}
        restart: always
        command:
          - "postgres"
          - "-c"
          - "shared_preload_libraries=pg_tle"
        environment:
            CI_ENVIRONMENT: ${CI_ENVIRONMENT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_OTHER_USER: ${POSTGRES_OTHER_USER}
            POSTGRES_OTHER_PASSWORD: ${POSTGRES_OTHER_PASSWORD}
            TZ: ${TZ}
        ports:
            - ${database_default_port}:5432
        volumes:
            - ./inpostgis:/inpostgis
            - ${OUTPOSTGIS}:/outpostgis
            - ./pgdata:/var/lib/postgresql/data
